Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: true
  Max: 120
  AllowURI: true
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/PredicateName:
  Enabled: false
